language: node_js
node_js:
- lts/*
install:
- npm install
script:
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIZPUTT2QS2CAQW3Q
  secret_access_key:
    secure: xW//xAZqSZk2XGtQ8vOEEeogdXUfAPqMrybtIr24l6ShRMTIhi4OOJP7Y+dKL6CoFW5A9a+LjiJMP+KeJQFsdtTFIVHlM269zU1K18kxnO2xv1qs0V//OGK2oqF9PX0i0hSGpADza/BWqlDGYgkPInSE+QKt27f/OhkSX8oJzvkHKTyZK5R9QG3DzOhoaYYm6+CBUDBRrnQ06ka4Oy4t4eD3Ej7Z0gTtM0ZRiP7rcV3kfI/+EPKrgQzbn7rAICLM9zaUE4vJrPnDywfS63jhqiOq77nLJLa9LNjwETZ0iSHcPby806xOilKI5b0p+29lkWVUEtg0bQKg7cwzfpCJarxGn+QxxZY+Rhv9bo06+JgfNG2nrjKxqcp010GVB+71dxCm6ajhne43rnmLo8zkTmYujNtqe1SvKKX8+DxFZ9yUnNvh3LwO9rIRKQeNNFc3zS6huDcxz24r2uqoqUL+yPzIbR1kpQAi631f7X7b7pGC44lO8nMgecLlH/OCdcy1zI76gs6iQa7+5tiOYKCRlfudmxb91CCCwhy+QtcaFihPkl18LKtGM7QH4R099s6xoI4t+BV4EJDtofF19qdbodarTnvrcZuYIc6ZmF9EfaJ3qNIypO5sAUYOm6IANoNyB5FnK65f6UEUKL1ZzhDpxnCrxHsU5wS1+66NqgCEVHA=
  bucket: dndnext-sheet
  local_dir: dist
  acl: 'public_read'
  on:
    branch: master
    repo: sesopenko/dndnext-sheet
